// <copyright file="ClientMessageTypesTest.TypesGet.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Valker.PlayOnLan.Server.Messages.Client
{
    public partial class ClientMessageTypesTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ClientMessageTypesTest))]
public void TypesGet748()
{
    Type[] types;
    types = this.TypesGet();
    Assert.IsNotNull((object)types);
    Assert.AreEqual<int>(7, types.Length);
    Assert.IsNotNull((object)(types[0]));
    Assert.IsNotNull((object)(types[1]));
    Assert.IsNotNull((object)(types[2]));
    Assert.IsNotNull((object)(types[3]));
    Assert.IsNotNull((object)(types[4]));
    Assert.IsNotNull((object)(types[5]));
    Assert.IsNotNull((object)(types[6]));
}
    }
}
