// <copyright file="ServerImplTest.RegisterNewParty.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Valker.PlayOnLan.Api.Communication;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Valker.PlayOnLan.Server
{
    public partial class ServerImplTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ServerImplTest))]
[ExpectedException(typeof(ArgumentException))]
public void RegisterNewPartyThrowsArgumentException60()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      ServerImpl serverImpl;
      PartyStatus i;
      IMessageConnector[] iMessageConnectors = new IMessageConnector[1];
      serverImpl =
        new ServerImpl((IEnumerable<IMessageConnector>)iMessageConnectors);
      disposables.Add((IDisposable)serverImpl);
      i = this.RegisterNewParty
              (serverImpl, (IClientInfo)null, (string)null, (string)null);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ServerImplTest))]
[ExpectedException(typeof(ArgumentException))]
public void RegisterNewPartyThrowsArgumentException664()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      ServerImpl serverImpl;
      PartyStatus i;
      IMessageConnector[] iMessageConnectors = new IMessageConnector[0];
      serverImpl =
        new ServerImpl((IEnumerable<IMessageConnector>)iMessageConnectors);
      disposables.Add((IDisposable)serverImpl);
      i = this.RegisterNewParty
              (serverImpl, (IClientInfo)null, (string)null, (string)null);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ServerImplTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void RegisterNewParty01()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      ServerImpl serverImpl;
      PartyStatus i;
      IMessageConnector[] iMessageConnectors = new IMessageConnector[251];
      serverImpl =
        new ServerImpl((IEnumerable<IMessageConnector>)iMessageConnectors);
      disposables.Add((IDisposable)serverImpl);
      i = this.RegisterNewParty
              (serverImpl, (IClientInfo)null, (string)null, (string)null);
      disposables.Dispose();
    }
}
    }
}
