
// This file has been generated by the GUI designer. Do not modify.
namespace GtkClient
{
	public partial class MainForm
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkClient.MainForm
			this.Name = "GtkClient.MainForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
