// <copyright file="AcceptNewPartyMessageTest.GameTypeGet.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Valker.PlayOnLan.Server.Messages.Server
{
    public partial class AcceptNewPartyMessageTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AcceptNewPartyMessageTest))]
public void GameTypeGet177()
{
    string s;
    AcceptNewPartyMessage s0 = new AcceptNewPartyMessage();
    s0.RequesterName = (string)null;
    s0.GameType = (string)null;
    s0.AccepterName = (string)null;
    s = this.GameTypeGet(s0);
    Assert.AreEqual<string>((string)null, s);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.RequesterName);
    Assert.AreEqual<string>((string)null, s0.GameType);
    Assert.AreEqual<string>((string)null, s0.AccepterName);
}
    }
}
