// <copyright file="AcceptNewPartyMessageTest.Constructor.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Valker.PlayOnLan.Server.Messages.Server
{
    public partial class AcceptNewPartyMessageTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AcceptNewPartyMessageTest))]
public void Constructor905()
{
    AcceptNewPartyMessage acceptNewPartyMessage;
    acceptNewPartyMessage =
      this.Constructor((string)null, (string)null, (string)null);
    Assert.IsNotNull((object)acceptNewPartyMessage);
    Assert.AreEqual<string>((string)null, acceptNewPartyMessage.RequesterName);
    Assert.AreEqual<string>((string)null, acceptNewPartyMessage.GameType);
    Assert.AreEqual<string>((string)null, acceptNewPartyMessage.AccepterName);
}
    }
}
