// <copyright file="MessageTest.ToString01.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Valker.PlayOnLan.Server.Messages.Server;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Valker.PlayOnLan.Server.Messages.Client;

namespace Valker.PlayOnLan.Server.Messages
{
    public partial class MessageTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MessageTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void ToString01296()
{
    string s;
    RetrieveSupportedGamesMessage s0 = new RetrieveSupportedGamesMessage();
    s = this.ToString01((Message)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(MessageTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void ToString01128()
{
    string s;
    AcknowledgeDropMessage s0 = new AcknowledgeDropMessage();
    s = this.ToString01((Message)s0);
}
    }
}
