// <copyright file="ServerMessageTest.Execute.g.cs" company="Kelman Ltd">Copyright © Kelman Ltd 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Valker.PlayOnLan.Server;
using Valker.PlayOnLan.Api.Communication;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Moles;
using Valker.PlayOnLan.Server.Messages.Server.Moles;

namespace Valker.PlayOnLan.Server.Messages.Server
{
    public partial class ServerMessageTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ServerMessageTest))]
public void Execute796()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SServerMessage sServerMessage;
      sServerMessage = new SServerMessage();
      this.Execute((ServerMessage)sServerMessage, 
                   (IServerMessageExecuter)null, (IClientInfo)null);
    }
}
    }
}
